site_name: Manchester HacSpace - Proxon MF70
pages:
- Home: index.md
- Sub Pages:
    - Auto Leveling: AutoLeveling.md
    - Control Board: ControlBoard.md
    - Milling: Milling.md
    - Circuit Diagrams: CircuitDiagrams.md

theme: slate
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
